### ISSUE TITLE
Do we still have the notion of a "Controller Document"?

### ISSUE THREAD

**Issue by iherman** [w3c/cid#132]
The title of the document has changed, but the concept of a "controller document" is still part of the specification, both as a section title ([§2.1](https://www.w3.org/TR/controller-document/#controller-documents)) and through the references to the term. Is that o.k.? Shouldn't there be a general change from a "Controller Document" to "Controlled Identifier Document" everywhere (maybe, in some cases, simply "Identifier Document")?

**Comment by msporny** [comment]
Yes, all mentions of "controller document" should have been changed to "controlled identifier document". If that's not the case, it's a bug and needs to be fixed.

**Comment by msporny** [comment]
PR #134 was raised to address this issue, the PR has been merged, closing.
